name: 'PHP Code Style (phpcs)'
description: 'PHPCS run'
author: 'David Lumaye (chindit)'
branding:
  icon: 'eye'
  color: 'green'
inputs:
  dir:
    description: 'Folder to check code style'
    required: false
    default: '.'
  extensions:
    description: 'List of extensions to check code style'
    required: false
    default: 'php,module,inc,install,test,profile,theme,css,info,txt,md,yml'
  standard:
    description: 'Standard used to check code style'
    required: false
    default: 'DrupalPractice'
  installed_paths:
    description: 'Location of the sniffs'
    required: false
    default: 'vendor/drupal/coder/coder_sniffer'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dir }} 
    - ${{ inputs.extensions }}
    - ${{ inputs.standard }}
    - ${{ inputs.installed_paths }}
